services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=finance_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=finance_db
      - MYSQL_USER=finance_user
      - MYSQL_PASSWORD=mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge